# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
