# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
