# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20170610_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
