# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_auto_20170627_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.FloatField(max_length=8),
        ),
    ]
