# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0009_auto_20170628_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.TextField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
