# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0011_auto_20170628_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question1',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
